// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/services-page/Current.tsx": () => import("../components/mockups/services-page/Current.tsx"),
  "./components/mockups/services-page/Refreshed.tsx": () => import("../components/mockups/services-page/Refreshed.tsx")
};
